server.port = 9090
spring.application.name=payment-gateway-service
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [requestId=%X{requestId}] %msg%n

spring.datasource.url=jdbc:postgresql://localhost:5432/nexaroPayDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.dbcp2.max-wait-millis=30000
spring.datasource.dbcp2.validation-query=/* ping */ select 1
spring.datasource.dbcp2.validation-query-timeout=30

spring.jpa.hibernate.ddl-auto=update